### ISSUE TITLE
Results do not match other implementations

### ISSUE THREAD

**Issue by cburgmer** [pacifica/python-jsonpath2#35]
The following queries provide results that do not match those of other implementations of JSONPath
(compare https://cburgmer.github.io/json-path-comparison/):

- [ ] `$.2`
  Input:
  ```
  {"a": "first", "2": "second", "b": "third"}
  ```
  Expected output:
  ```
  ["second"]
  ```
  Error:
  ```
  line 1:2 mismatched input '2' expecting {'*', ID}
  ValueError("line 1:2 mismatched input '2' expecting {'*', ID}")
  ```

- [ ] `$[::2]`
  Input:
  ```
  ["first", "second", "third", "forth", "fifth"]
  ```
  Expected output:
  ```
  ["first", "third", "fifth"]
  ```
  Actual output:
  ```
  ["first", "second"]
  ```

- [ ] `$[?(@.key==42)]`
  Input:
  ```
  [{"key": 0}, {"key": 42}, {"key": -1}, {"key": 41}, {"key": 43}, {"key": 42.0001}, {"key": 41.9999}, {"key": 100}, {"some": "value"}]
  ```
  Expected output:
  ```
  [{"key": 42}]
  ```
  Error:
  ```
  line 1:10 extraneous input '=' expecting {'@', '$', 'true', 'false', 'null', '{', '[', STRING, NUMBER}
  ValueError("line 1:10 extraneous input '=' expecting {'@', '$', 'true', 'false', 'null', '{', '[', STRING, NUMBER}")
  ```

- [ ] `$[?(@.key>42)]`
  Input:
  ```
  [{"key": 0}, {"key": 42}, {"key": -1}, {"key": 41}, {"key": 43}, {"key": 42.0001}, {"key": 41.9999}, {"key": 100}]
  ```
  Expected output:
  ```
  [{"key": 43}, {"key": 42.0001}, {"key": 100}]
  ```
  Actual output:
  ```
  []
  ```

- [ ] `$[?(@.key)]`
  Input:
  ```
  [{"some": "some value"}, {"key": "value"}]
  ```
  Expected output:
  ```
  [{"key": "value"}]
  ```
  Actual output:
  ```
  []
  ```

- [ ] `$['key']`
  Input:
  ```
  {"key": "value"}
  ```
  Expected output:
  ```
  ["value"]
  ```
  Error:
  ```
  line 1:2 token recognition error at: '''
  ValueError("line 1:2 token recognition error at: '''")
  ```

For reference, the output was generated by the program in https://github.com/cburgmer/json-path-comparison/tree/master/implementations/Python_jsonpath2.

**Comment by markborkum** [comment]
@cburgmer, Thank you for sharing your results. Next time, to help facilitate our project management workflow, please try to submit each result as a separate GitHub issue.

The table below addresses each of your results individually.

| Result # | Original | Recommendation | Note # |
|-|-|-|-|
| 1 | `$.2` | `$["2"]` | 1 |
| 2 | `$[::2]` | N/A | 2 |
| 3 | `$[?(@.key==42)]` | `$[*][?(@.key=42)]` | 3, 4 |
| 4 | `$[?(@.key>42)]` | `$[*][?(@.key>42)]` | 4 |
| 5 | `$[?(@.key)]` | `$[*][?(@.key)]` | 4 |
| 6 | `$['key']` | `$["key"]` | 5 |

**Notes:**

1. This implementation of JSONPath shares the ECMAScript convention for bare-word variable names: the first character must be a either an underscore (`_`) or a letter (`A-Z` or `a-z`).

   In the ANTLR4 grammar, the corresponding production rule is:

   https://github.com/pacifica/python-jsonpath2/blob/master/jsonpath2/parser/JSONPath.g4#L99-L101

   To use a number as the key for a JSON object, write the JSONPath using the subscript syntax, e.g., `$["n"]`, where `n` is the number.

2. **You found a bug. Thank you!** The test suite covered the object-oriented representation of the array slice syntax, but not the corresponding parser code, which contained a bug. See https://github.com/pacifica/python-jsonpath2/pull/37 for details.

3. This implementation of JSONPath uses `=` as the syntax for the strict equality comparison operator for JSON values.

4. Other implementations of JSONPath automatically iterate over the elements/values of JSON arrays/objects in the current scope.

   This implementation of JSONPath provides a wildcard `*` operator to make the iteration explicit, allowing both the elements/values and the JSON arrays/objects to be uniquely identified.

   For example, given `{"key":[1,2,3,4,5]}` as input:

   | Example # | JSONPath | Outputs |
   |-|-|-|
   | 1 | `$` | `{"key":[1,2,3,4,5]}` |
   | 2 | `$["key"]` | `[1,2,3,4,5]` |
   | 3 | `$["key"][2]` | `3` |
   | 4 | `$["key"][?(@ > 3)]` | *No outputs because `@` is currently identified with `$["key"]`.* |
   | 5 | `$["key"][*]` | `1`, `2`, `3`, `4`, and `5` |
   | 6 | `$["key"][*][?(@ > 3)]` | `4` and `5` |
   | 7 | `$["key"][*][?(@ > $["key"][2])]` | `4` and `5` |
   | 8 | `$["key"][?(@[*] > @[2])]` | `[1,2,3,4,5]` |
   | 9 | `$[?(@["key"][*] > @["key"][2])]` | `{"key":[1,2,3,4,5]}` |
   | 10 | `$[?(@["key"][?(@[*] > @[2])])]` | `{"key":[1,2,3,4,5]}` |

5. This implementation of JSONPath shares the JSON convention for string quotation: double quote (`"`) characters only.

**Comment by cburgmer** [comment]
Thanks for the detailed clarification.

I'm still in the process of understanding how much the different implementations value a "standardisation" of JSONPath. I am going to continue to poke into corner cases and surface different interpretation of the original post by Goessner, but will try to adapt my communication to the goals of the respective implementation, e.g. when filing bugs. (It might help if you clarify in the README those cases where you intentionally detach yourself from the other implementations.)

I welcome feedback on how to take this forward if we do agree somewhat on reducing the differences in the JSONPath implementations towards a shared understanding of JSONPath.

**Comment by dmlb2000** [comment]
Seems like other's are trying to specify querying JSON documents as well. http://jmespath.org/specification.html They didn't even want to get close to calling themselves jsonpath (not sure what jmes might be).
